### PR TITLE
Improve index page load time by optimising image assets

### PR DESCRIPTION
**Pull request by siwalikm**
**Issue:** While viewing the glimpse-editor.org website homepage I noticed it is making web requests for huge image assets from the server but showing a scaled-down versions for all of them.

Hence initial page lead is slow over 3g networks as we're downloading close to 3MB resources before the page is even ready.

**Solution:** Optimised all the images assets shown in the homepage to maintain clarity but scale them down to approx 800px width and original aspect ratio.

New resource size is around ~3MB~ 858kB

image
Here's a screenshot of the app's before/after. Let me know if you have any comments.

### CODE REVIEW

**Comment by siwalikm** [comment]
@TrechNex can you have a look at this?

**Comment by TrechNex** [comment]
Looks good to me. The main issue would be the Flatpak images, as they're actually used by Flathub.

Best solution for that would be to provide the scaled down versions as separate files in the same directory.

**Comment by TrechNex** [comment]
Scratch that, we use the PNGs on Flathub, so this is actually fine :)

**Comment by TrechNex** [comment]
Thank you for your help with this, it's much appreciated. Our slow home page is something people have been complaining to us about :)

**Comment by siwalikm** [comment]
Thanks for approving. I love this project so doing my part. :)
If there are any issues on the website you need help with, tag me.

**Pull request merged**
