### PR TITLE
New Theme

### PR DESCRIPTION
**Pull request by BrainBlasted**
Things left to take care of:

* [x] Create a proper list page for the "Posts" section
* [x] Ensure the site is accessible

### CODE REVIEW

**Comment by BrainBlasted** [comment]
I recommend trying this out on localhost, as Netlify isn't serving the CSS correctly.

**Comment by ognarb** [comment]
Sorry for the late review :/ and first code review I do on github :(

Website looks nice overall and is responsive.

I have two nick pick about the css.

I don't recommend using inline css and  I can see generated css files in the pr, I think it would be better to generate it in the ci and store the corresponding scss in git.

Another problems that is not related to this pr is that the image don't have an alt attribute, this is not optimal for screen reader.

And I would add a bit more content and screenshots in the homepage showing some features and the UI of Glimpse. You want to make the visitor click on the future download button and donation button ;)

**Comment by BrainBlasted** [comment]
Added the alt text and fixed the list template.

**Comment by BrainBlasted** [comment]
> I don't recommend using inline css and I can see generated css files in the pr, I think it would be better to generate it in the ci and store the corresponding scss in git.

Can you create an issue for this? For now, I'll merge as-is since we plan to release tomorrow.

**Pull request merged**
