### PR TITLE
update design to include branding elements

### PR DESCRIPTION
**Pull request by zachkrall**
Hi ☺️

This pull request uses colors and branding elements defined in [glimpse-editor/branding](https://github.com/glimpse-editor/branding). There aren't any changes to page/content structure or bootstrap dependency.

- Adds blue gradient from branding guidelines to navigation bar
- Adds `divider.html` partial which creates the wavy separation between gradient and content sections. (Generated with [getwaves.io](https://getwaves.io/))
- Adds [Manrope 3](https://github.com/sharanda/manrope) typeface defined in branding guidelines.
- Moves `download` link in navigation bar to end as call-to-action button.

Screen Shot 2020-06-28 at 9 51 06 PM

### CODE REVIEW

**Comment by TrechNex** [comment]
This looks amazing, and I just tested it locally on my own setup :)

Just canvassing some opinions around the project before proceeding. Thank you for this very cool work. If we merge this would you prefer me to credit you as a "documenter" or an "artist" in the Glimpse app?

**Comment by zachkrall** [comment]
@TrechNex cool :) please let me know if there are any changes you might need so that it fits the tone correctly. 

I think I'd prefer the label "artist."

**Comment by Member1221** [comment]
I would like to have @jaames and @estatra's opinions on this before we proceed. They are the main design related folks working on Glimpse.

**Comment by estatra** [comment]
It's just that that logo border hurts my soul, such poor visibility in small scales (an ongoing discussion on another issue that we're still trying to solve). I've increased it by a factor of 2 for better readability.

Overall, the mockup LGTM. 

Needs @jaames and Governance input. If approved, I'll provide the source file for @zachkrall to work with.

better-logo-readability

**Comment by zachkrall** [comment]
@estatra I didn't want to interfere with any existing assets like the logo or screenshots but that new border around the logo looks incredible imo

**Comment by estatra** [comment]
@zachkrall I've found some typographic alignment and optical weight/balance problems on your mockup, in case this pass, I would like to ask for you to fix them. Need James to review my point.

The left _Download_ button could perhaps have an extra appendix for better weight distribution, with an arrow pointing down, signaling a download action, because of it being a common recognizable sign, as opposed of just an arrow pointing to the right.

Measurements were done with pixel perfection.

I've also noticed that the Manrope font has a vertical misalignment in it's lower case set, which is weird. Most people won't notice I think.

Please click the images to view full size.

**Comment by zachkrall** [comment]
@estatra 

we could reduce the padding on the bottom of those buttons to account for the alignment issues with manrope. maybe something like `padding: .25rem .5rem .25rem .48rem;` what percentage larger is the bottom padding compared to the top in your measurement? the current padding is `padding:.5rem .25rem .5rem .25rem;`

since bootstrap is already a part of the project, what if we used the bootstrap [download icon](https://icons.getbootstrap.com/icons/download/)?

**Comment by jaames** [comment]
Looks pretty good! Nice job!

**Comment by estatra** [comment]
@zachkrall 

> [...] what percentage larger is the bottom padding compared to the top in your measurement?

It's the inverse, the top is larger. The vertical measure.

- The left _Download_ button padding is ~17.42% bigger than the bottom.
- The right _Download_ button padding is ~45.21% bigger than the bottom.
- Horizontal padding is only a problem on the left download button, because of the arrow, on the right padding, which is ~11.40% larger than the left padding. Measured tip of the arrow to border.

Keep in mind that I don't consider upper case letters, I measure the lower case entire body as good practice, each designer have their view, teachings, etc. This is mine and how I determine optical weight and alignment.

Also to consider that I've used the "O" lower case letter as my anchor since Manrope has misaligned lower case letters in it's design...

> since bootstrap is already a part of the project, what if we used the bootstrap [download icon](https://icons.getbootstrap.com/icons/download/)?

Sounds good to me if the aesthetics is preserved.

You have my bless and seems like James too, so we just need governance input on the bootstrap thing, since I'm not a webdev veteran.

**Comment by zachkrall** [comment]
@estatra bootstrap was added before this PR :) I don’t actually use it much personally but didn’t want to edit too much of the existing site.

**Comment by estatra** [comment]
> @estatra bootstrap was added before this PR :) I don’t actually use it much personally but didn’t want to edit too much of the existing site.

I know, my message was directed at governance mostly. BTW, awesome work so far!

**Comment by zachkrall** [comment]
@estatra i misunderstood! 
thanks :)

**Comment by TrechNex** [comment]
@estatra medium/long term I agree that the logo needs updating. The sticker logo mostly exists for now to help people who are using desktop shortcuts on a dark background, and to give us more flexibility with web design.

I also agree that we need better screenshots after this thing is merged and (ideally) before 0.2.0 is released next month. For now I'm using placeholder images. The two screenshots are the same ones we use for Flathub, the handshake is a stock image and the Windows screenshot is a placeholder until I've written the new installer with its graphical elements.

**Comment by estatra** [comment]
@TrechNex I see, cool. 

@zachkrall Are you able to commit the optical weight/balance adjustments?

**Comment by jaames** [comment]
Yeah, the gradient kinda clashes with the logo a bit now that I've looked at it more. 

If you think it would work, you could maybe try a more neutral dark background color instead of the blue/purple gradient, perhaps using the gradient as a subtle accent instead

**Comment by zachkrall** [comment]
@estatra I decreased the top padding and separated the text into a separate `<span>` as the icon. their padding values are:
text span: `padding:0.35em 0.60em 0.5em 0.75em;`
icon span : `padding:0em 0.75em 0em 0em; transform:translate(0,-0.03em);`

@jaames I replaced the gradient with the `#000012` color value from the logo svg.

Screen Shot 2020-06-30 at 6 24 05 PM

**Comment by estatra** [comment]
@zachkrall Is it not possible to to center/align the text on your side? 

The left download button is much better (still not fully aligned tho) but the right one gives a 3D optical sense because of the text being hanging a bit lower on the box.

right-download-button png

left-download-button

proportion-problem

**Comment by jaames** [comment]
(I gotta leave feedback to estatra unfortunately, the game I work on for my day-job is going into a public beta this week so it's all hands on deck and I can't really dedicate much time to this. There's definitely things I'd like to play around with and tweak, but imo this is already significantly better than the current Glimpse website, so I welcome the change nevertheless!)

**Comment by estatra** [comment]
> (I gotta leave feedback to estatra unfortunately, the game I work on for my day-job is going into a public beta this week so it's all hands on deck and I can't really dedicate much time to this. There's definitely things I'd like to play around with and tweak, but imo this is already significantly better than the current Glimpse website, so I welcome the change nevertheless!)

All good @jaames. @zachkrall If you're busy or don't want to mess too much with the website internals, your design is good to go on my part. I suggest using the original gradient, the dark one seem a bit off. If you can make the changes with the optical balance and alignment (download buttons) that would be a plus, but like a said, if it's not possible at the moment, you're good to go.

**Comment by TrechNex** [comment]
Okay, I will wait on the nod from @zachkrall before retesting locally and then merging. Thanks for the help @estatra & @jaames :)

**Comment by zachkrall** [comment]
Hi @TrechNex 
Sorry for the delay. I've reverted the background color to the original blue gradient and removed the icon in the download button. :)

**Comment by TrechNex** [comment]
Thank you for this amazing work @zachkrall - it's live now :)

Did you want me to link to your website in the next blog post? I noticed your Twitter account is protected, so my apologies if mentioning you from the project account wasn't cool.

**Comment by zachkrall** [comment]
@TrechNex Linking to my website or twitter is ok :)

**Pull request merged**
